# Generated by Django 6.0.4 on 2026-06-26 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCwiczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True, null=True)),
                ('wideo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fizjoterapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('specka', models.CharField(max_length=150, verbose_name='Specjalizacja')),
                ('tytul', models.CharField(max_length=20, verbose_name='Tytuł Naukowy')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='Imię pacjenta')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko pacjenta')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa programu')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Zalecenia ogólne')),
                ('data_startu', models.DateField(verbose_name='Data rozpoczęcia')),
                ('data_konca', models.DateField(verbose_name='Data zakończenia')),
                ('czestotliwosc_tygodniowa', models.PositiveSmallIntegerField(default=3, help_text='Ile sesji w tygodniu pacjent ma do wyrobienia')),
                ('fizjoterapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programy', to='fizjoapp.fizjoterapeuta', verbose_name='Fizjoterapeuta odpowiedzialny za pacjenta')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programy', to='fizjoapp.pacjent', verbose_name='Pacjent')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCwiczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(default=3)),
                ('powtorzenia', models.CharField(max_length=50)),
                ('cwiczenie_bazowe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fizjoapp.globalcwiczenie')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwiczenia', to='fizjoapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='TreningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wykonania', models.DateField(auto_now_add=True)),
                ('skala_bol', models.IntegerField(help_text='Oceń trudność treningu (odczuwany ból) w skali od 1 do 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pacjent_kom', models.TextField(blank=True, help_text='Opisz jak się czułeś podczas ćwiczeń.', null=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logi_treningow', to='fizjoapp.pacjent')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logi', to='fizjoapp.program')),
            ],
            options={
                'verbose_name': 'Log Treningu',
                'verbose_name_plural': 'Logi Treningów',
                'ordering': ['-data_wykonania'],
                'unique_together': {('pacjent', 'program', 'data_wykonania')},
            },
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('status', models.CharField(choices=[('propozycja', 'Propozycja Pacjenta'), ('zatwierdzona', 'Zatwierdzona'), ('odrzucona', 'Odrzucona')], default='propozycja', max_length=20)),
                ('fizjoterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='fizjoapp.fizjoterapeuta')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='fizjoapp.pacjent')),
            ],
        ),
        migrations.CreateModel(
            name='ZrobioneCwiczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wykonane', models.BooleanField(default=False)),
                ('cwiczenie_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fizjoapp.programcwiczenie')),
                ('trening_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wykonane_cwiczenia', to='fizjoapp.treninglog')),
            ],
        ),
        migrations.CreateModel(
            name='FizjoPacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('zaakceptowany', 'Zaakceptowany')], default='zaakceptowany', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('fizjoterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_z_pacjentami', to='fizjoapp.fizjoterapeuta')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_z_fizjo', to='fizjoapp.pacjent')),
            ],
            options={
                'verbose_name': 'Relacja fizjo-pacjent',
                'verbose_name_plural': 'Relacje fizjo-pacjent',
                'unique_together': {('fizjoterapeuta', 'pacjent')},
            },
        ),
    ]
