# Generated by Django 6.0.5 on 2026-06-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fizjoterapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('specka', models.CharField(max_length=150, verbose_name='Specjalizacja')),
                ('tytul', models.CharField(max_length=20, verbose_name='Tytuł Naukowy')),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='Imię pacjenta')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko pacjenta')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('fizjo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjenci', to='fizjoapp.fizjoterapeuta', verbose_name='Fizjoterapeuta odpowiedzialny za pacjenta')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa programu')),
                ('opis', models.TextField(verbose_name='Opis')),
                ('data', models.DateField(auto_now_add=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programy', to='fizjoapp.pacjent', verbose_name='Pacjent')),
            ],
        ),
    ]
