# Generated by Django 6.0.5 on 2026-06-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0002_fizjoterapeuta_user_pacjent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='fizjo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacjenci', to='fizjoapp.fizjoterapeuta', verbose_name='Fizjoterapeuta odpowiedzialny za pacjenta'),
        ),
    ]
