# Generated by Django 6.0.2 on 2026-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0003_alter_pacjent_fizjo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacjent_nazwa', models.CharField(default='Pacjent', max_length=100)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
            ],
        ),
    ]
