# Generated by Django 6.0.4 on 2026-06-18 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0005_wizyta_lekarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wykonania', models.DateField(auto_now_add=True)),
                ('skala_bol', models.IntegerField(help_text='Oceń trudność treningu (odczuwany ból) w skali od 1 do 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pacjent_kom', models.TextField(blank=True, help_text='Opisz jak się czułeś podczas ćwiczeń.', null=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logi_treningow', to='fizjoapp.pacjent')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fizjoapp.program')),
            ],
            options={
                'verbose_name': 'Log Treningu',
                'verbose_name_plural': 'Logi Treningów',
                'ordering': ['-data_wykonania'],
            },
        ),
        migrations.CreateModel(
            name='FizjoPacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('zaakceptowany', 'Zaakceptowany')], default='zaakceptowany', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('fizjoterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_z_pacjentami', to='fizjoapp.fizjoterapeuta')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_z_fizjo', to='fizjoapp.pacjent')),
            ],
            options={
                'verbose_name': 'Relacja fizjo-pacjent',
                'verbose_name_plural': 'Relacje fizjo-pacjent',
                'unique_together': {('fizjoterapeuta', 'pacjent')},
            },
        ),
    ]
