# Generated by Django 6.0.2 on 2026-06-19 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0006_treninglog_fizjopacjent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cwiczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_cwiczenia', models.CharField(max_length=255)),
                ('serie', models.IntegerField(default=3)),
                ('powtórzenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OcenaCwiczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skala_bolu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('data_oceny', models.DateTimeField(auto_now_add=True)),
                ('cwiczenie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocena', to='fizjoapp.cwiczenie')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTreningowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('fizjoterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plany', to='fizjoapp.fizjoterapeuta')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plany', to='fizjoapp.pacjent')),
            ],
        ),
        migrations.AddField(
            model_name='cwiczenie',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwiczenia', to='fizjoapp.plantreningowy'),
        ),
    ]
