# Generated by Django 6.0.4 on 2026-06-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0007_cwiczenie_ocenacwiczenia_plantreningowy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocenacwiczenia',
            options={'ordering': ['-data_oceny'], 'verbose_name': 'Ocena ćwiczenia', 'verbose_name_plural': 'Oceny ćwiczeń'},
        ),
        migrations.AddField(
            model_name='ocenacwiczenia',
            name='pacjent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oceny', to='fizjoapp.pacjent'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='pacjent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizyty', to='fizjoapp.pacjent'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='powod',
            field=models.TextField(blank=True, null=True, verbose_name='Powód wizyty'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('oczekujaca', 'Oczekująca'), ('zaakceptowana', 'Zaakceptowana'), ('odrzucona', 'Odrzucona'), ('zablokowana', 'Zablokowana')], default='oczekujaca', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocenacwiczenia',
            name='cwiczenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='fizjoapp.cwiczenie'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='lekarz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wizyty_jako_lekarz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='pacjent_nazwa',
            field=models.CharField(blank=True, default='Pacjent', max_length=200),
        ),
    ]
