# Generated by Django 6.0.4 on 2026-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0008_alter_ocenacwiczenia_options_ocenacwiczenia_pacjent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='kod_pacjenta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kod pacjenta'),
        ),
        migrations.AlterField(
            model_name='fizjopacjent',
            name='status',
            field=models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('zaakceptowany', 'Zaakceptowany'), ('odrzucony', 'Odrzucony')], default='zaakceptowany', max_length=20),
        ),
    ]
