# Generated by Django 6.0.4 on 2026-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizjoapp', '0009_pacjent_kod_pacjenta_alter_fizjopacjent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreningowy',
            name='czas_trwania_tygodnie',
            field=models.IntegerField(default=4, verbose_name='Czas trwania (tygodnie)'),
        ),
        migrations.AddField(
            model_name='plantreningowy',
            name='sesje_tygodniowo',
            field=models.IntegerField(default=3, verbose_name='Sesji w tygodniu'),
        ),
    ]
